// Generated by tools/export_stations.py from termbeat/app.py - do not edit.
export const DEFAULT_STATIONS = [
  {
    "id": "groovesalad",
    "station": "Groove Salad",
    "freq": "88.5",
    "url": "https://ice1.somafm.com/groovesalad-128-mp3",
    "bitrate": "128kbps",
    "genre": "CHILL",
    "signal": "99%",
    "track": "Ambient Beats & Chilled Grooves [SomaFM]",
    "provider": "somafm"
  },
  {
    "id": "dronezone",
    "station": "Drone Zone",
    "freq": "91.3",
    "url": "https://ice1.somafm.com/dronezone-128-mp3",
    "bitrate": "128kbps",
    "genre": "SPACE",
    "signal": "96%",
    "track": "Atmospheric Ambient Space Music [SomaFM]",
    "provider": "somafm"
  },
  {
    "id": "deepspaceone",
    "station": "Deep Space One",
    "freq": "92.8",
    "url": "https://ice1.somafm.com/deepspaceone-128-mp3",
    "bitrate": "128kbps",
    "genre": "COSMIC",
    "signal": "95%",
    "track": "Deep Space Ambient & Interstellar Soundscapes [SomaFM]",
    "provider": "somafm"
  },
  {
    "id": "missioncontrol",
    "station": "Mission Control",
    "freq": "94.2",
    "url": "https://ice1.somafm.com/missioncontrol-128-mp3",
    "bitrate": "128kbps",
    "genre": "NASA",
    "signal": "97%",
    "track": "Ambient Music Mixed with Live NASA Comms [SomaFM]",
    "provider": "somafm"
  },
  {
    "id": "plaza",
    "station": "Nightwave Plaza",
    "freq": "96.0",
    "url": "https://radio.plaza.one/mp3",
    "bitrate": "128kbps",
    "genre": "VAPOR",
    "signal": "98%",
    "track": "24/7 Aesthetic Vaporwave & Future Funk [Plaza.one]",
    "provider": "plaza"
  },
  {
    "id": "vaporwaves",
    "station": "Vaporwaves",
    "freq": "97.5",
    "url": "https://ice1.somafm.com/vaporwaves-128-mp3",
    "bitrate": "128kbps",
    "genre": "SYNTH",
    "signal": "95%",
    "track": "Aesthetic Retro Synthesizer Vibes [SomaFM]",
    "provider": "somafm"
  },
  {
    "id": "defcon",
    "station": "Def Con Radio",
    "freq": "98.9",
    "url": "https://ice1.somafm.com/defcon-128-mp3",
    "bitrate": "128kbps",
    "genre": "HACK",
    "signal": "98%",
    "track": "Music for Hackers and Coders [SomaFM]",
    "provider": "somafm"
  },
  {
    "id": "cliqhop",
    "station": "cliqhop idm",
    "freq": "100.2",
    "url": "https://ice1.somafm.com/cliqhop-128-mp3",
    "bitrate": "128kbps",
    "genre": "IDM",
    "signal": "94%",
    "track": "Intelligent Dance Music & Glitch Beats [SomaFM]",
    "provider": "somafm"
  },
  {
    "id": "u80s",
    "station": "Underground 80s",
    "freq": "101.7",
    "url": "https://ice1.somafm.com/u80s-128-mp3",
    "bitrate": "128kbps",
    "genre": "NEWWAV",
    "signal": "95%",
    "track": "Early 80s UK Synthpop & New Wave [SomaFM]",
    "provider": "somafm"
  },
  {
    "id": "reyfm_lofi",
    "station": "REYFM Lo-Fi",
    "freq": "102.8",
    "url": "https://listen.reyfm.de/lofi_320kbps.mp3",
    "bitrate": "320kbps",
    "genre": "LOFI",
    "signal": "99%",
    "track": "24/7 Instrumental Lo-Fi & Chill Beats [REYFM]",
    "provider": "generic"
  },
  {
    "id": "suburbsofgoa",
    "station": "Suburbs of Goa",
    "freq": "103.9",
    "url": "https://ice1.somafm.com/suburbsofgoa-128-mp3",
    "bitrate": "128kbps",
    "genre": "WORLD",
    "signal": "93%",
    "track": "Desi Asian World Beats & Sitar Chill [SomaFM]",
    "provider": "somafm"
  },
  {
    "id": "beatblender",
    "station": "Beat Blender",
    "freq": "104.8",
    "url": "https://ice1.somafm.com/beatblender-128-mp3",
    "bitrate": "128kbps",
    "genre": "HOUSE",
    "signal": "92%",
    "track": "Deep House & Downtempo Grooves [SomaFM]",
    "provider": "somafm"
  },
  {
    "id": "radioparadise_main",
    "station": "Radio Paradise",
    "freq": "105.7",
    "url": "https://stream.radioparadise.com/mp3-128",
    "bitrate": "128kbps",
    "genre": "ECLTC",
    "signal": "99%",
    "track": "Eclectic Modern & Classic Rock, Electronica, World",
    "provider": "radioparadise"
  },
  {
    "id": "radioparadise_mellow",
    "station": "RP Mellow Mix",
    "freq": "106.4",
    "url": "https://stream.radioparadise.com/mellow-128",
    "bitrate": "128kbps",
    "genre": "MELLOW",
    "signal": "98%",
    "track": "Mellow Acoustic, Downtempo & Ambient Blend",
    "provider": "radioparadise"
  },
  {
    "id": "kexp",
    "station": "KEXP 90.3 Seattle",
    "freq": "90.3",
    "url": "https://kexp.streamguys1.com/kexp160.aac",
    "bitrate": "160kbps",
    "genre": "INDIE",
    "signal": "97%",
    "track": "Where the Music Matters [KEXP 90.3 FM]",
    "provider": "kexp"
  },
  {
    "id": "secretagent",
    "station": "Secret Agent",
    "freq": "107.9",
    "url": "https://ice1.somafm.com/secretagent-128-mp3",
    "bitrate": "128kbps",
    "genre": "SPY",
    "signal": "94%",
    "track": "The Soundtrack for Your Spy Life [SomaFM]",
    "provider": "somafm"
  }
];

export const THEMES = [
  {
    "name": "Classic Tuna",
    "frame": [
      70,
      95,
      145
    ],
    "title_bg": [
      24,
      42,
      82
    ],
    "title_fg": [
      255,
      255,
      255
    ],
    "deck_bg": [
      18,
      26,
      48
    ],
    "lcd_bg": [
      6,
      20,
      12
    ],
    "lcd_border": [
      32,
      75,
      48
    ],
    "lcd_dim": [
      38,
      115,
      55
    ],
    "lcd_bright": [
      55,
      255,
      95
    ],
    "accent": [
      0,
      220,
      255
    ],
    "warn": [
      255,
      210,
      40
    ]
  },
  {
    "name": "Cyberpunk",
    "frame": [
      170,
      45,
      140
    ],
    "title_bg": [
      46,
      16,
      68
    ],
    "title_fg": [
      255,
      255,
      255
    ],
    "deck_bg": [
      28,
      14,
      42
    ],
    "lcd_bg": [
      16,
      6,
      26
    ],
    "lcd_border": [
      110,
      32,
      95
    ],
    "lcd_dim": [
      120,
      45,
      105
    ],
    "lcd_bright": [
      0,
      240,
      255
    ],
    "accent": [
      255,
      25,
      140
    ],
    "warn": [
      255,
      220,
      40
    ]
  },
  {
    "name": "Amber CRT",
    "frame": [
      155,
      105,
      35
    ],
    "title_bg": [
      48,
      32,
      10
    ],
    "title_fg": [
      255,
      240,
      200
    ],
    "deck_bg": [
      32,
      20,
      8
    ],
    "lcd_bg": [
      20,
      12,
      4
    ],
    "lcd_border": [
      95,
      62,
      20
    ],
    "lcd_dim": [
      140,
      90,
      25
    ],
    "lcd_bright": [
      255,
      185,
      30
    ],
    "accent": [
      255,
      215,
      50
    ],
    "warn": [
      255,
      110,
      30
    ]
  },
  {
    "name": "Matrix",
    "frame": [
      30,
      115,
      50
    ],
    "title_bg": [
      8,
      38,
      16
    ],
    "title_fg": [
      220,
      255,
      230
    ],
    "deck_bg": [
      10,
      25,
      12
    ],
    "lcd_bg": [
      4,
      16,
      6
    ],
    "lcd_border": [
      22,
      85,
      38
    ],
    "lcd_dim": [
      35,
      120,
      50
    ],
    "lcd_bright": [
      50,
      255,
      85
    ],
    "accent": [
      110,
      255,
      145
    ],
    "warn": [
      240,
      230,
      40
    ]
  },
  {
    "name": "Synthwave",
    "frame": [
      115,
      60,
      165
    ],
    "title_bg": [
      40,
      18,
      68
    ],
    "title_fg": [
      255,
      230,
      255
    ],
    "deck_bg": [
      25,
      12,
      42
    ],
    "lcd_bg": [
      18,
      8,
      30
    ],
    "lcd_border": [
      98,
      42,
      125
    ],
    "lcd_dim": [
      145,
      60,
      120
    ],
    "lcd_bright": [
      255,
      95,
      185
    ],
    "accent": [
      255,
      165,
      45
    ],
    "warn": [
      255,
      220,
      50
    ]
  },
  {
    "name": "Blue Hour",
    "frame": [
      44,
      84,
      99
    ],
    "title_bg": [
      0,
      46,
      58
    ],
    "title_fg": [
      232,
      240,
      248
    ],
    "deck_bg": [
      13,
      28,
      33
    ],
    "lcd_bg": [
      0,
      16,
      21
    ],
    "lcd_border": [
      32,
      66,
      78
    ],
    "lcd_dim": [
      58,
      107,
      125
    ],
    "lcd_bright": [
      255,
      236,
      24
    ],
    "accent": [
      0,
      205,
      255
    ],
    "warn": [
      255,
      125,
      172
    ]
  },
  {
    "name": "Ultraviolet",
    "frame": [
      98,
      72,
      98
    ],
    "title_bg": [
      52,
      29,
      59
    ],
    "title_fg": [
      232,
      240,
      248
    ],
    "deck_bg": [
      30,
      19,
      34
    ],
    "lcd_bg": [
      18,
      7,
      22
    ],
    "lcd_border": [
      76,
      54,
      78
    ],
    "lcd_dim": [
      124,
      93,
      123
    ],
    "lcd_bright": [
      255,
      187,
      21
    ],
    "accent": [
      231,
      146,
      255
    ],
    "warn": [
      0,
      225,
      240
    ]
  },
  {
    "name": "Ember",
    "frame": [
      92,
      74,
      44
    ],
    "title_bg": [
      58,
      33,
      0
    ],
    "title_fg": [
      232,
      240,
      248
    ],
    "deck_bg": [
      33,
      21,
      13
    ],
    "lcd_bg": [
      21,
      9,
      0
    ],
    "lcd_border": [
      73,
      57,
      32
    ],
    "lcd_dim": [
      116,
      96,
      58
    ],
    "lcd_bright": [
      0,
      255,
      255
    ],
    "accent": [
      255,
      162,
      0
    ],
    "warn": [
      252,
      139,
      255
    ]
  },
  {
    "name": "Deep Field",
    "frame": [
      62,
      77,
      107
    ],
    "title_bg": [
      17,
      40,
      63
    ],
    "title_fg": [
      232,
      240,
      248
    ],
    "deck_bg": [
      16,
      24,
      38
    ],
    "lcd_bg": [
      3,
      12,
      27
    ],
    "lcd_border": [
      46,
      60,
      86
    ],
    "lcd_dim": [
      82,
      99,
      134
    ],
    "lcd_bright": [
      194,
      226,
      47
    ],
    "accent": [
      93,
      186,
      255
    ],
    "warn": [
      255,
      127,
      135
    ]
  }
];
