#!/usr/bin/env python3
"""Write the app's default stations and colour themes to extension/src/defaults.js,
so the browser extension and the terminal app can never drift apart.

Run after changing DEFAULT_PLAYLIST or THEMES:  python3 tools/export_stations.py
--check exits non-zero if the generated file is out of date (used by CI).
"""
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

from termbeat import app  # noqa: E402

OUT = os.path.join(ROOT, "extension", "src", "defaults.js")


def render() -> str:
    themes = [{k: v for k, v in t.items() if not k.startswith("_")} for t in app.THEMES]
    return (
        "// Generated by tools/export_stations.py from termbeat/app.py - do not edit.\n"
        f"export const DEFAULT_STATIONS = {json.dumps(app.DEFAULT_PLAYLIST, indent=2, ensure_ascii=False)};\n\n"
        f"export const THEMES = {json.dumps(themes, indent=2)};\n"
    )


def main() -> int:
    text = render()
    if "--check" in sys.argv:
        try:
            with open(OUT, encoding="utf-8") as f:
                current = f.read()
        except OSError:
            current = ""
        if current != text:
            print(f"{OUT} is out of date; run python3 tools/export_stations.py")
            return 1
        return 0
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(text)
    print(f"wrote {len(app.DEFAULT_PLAYLIST)} stations and {len(app.THEMES)} themes to {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
